# Generated by Django 5.1.3 on 2025-02-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_name_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='Anonymous', upload_to='images'),
        ),
    ]
